#!/bin/sh
set -e

if ! command -v R >/dev/null 2>&1; then
  echo "R executable not found" 1>&2
  exit 1
fi


export NVML_INCLUDE_DIR=$CUDA_HOME/include
export NVML_LIB_DIR=$CUDA_HOME/targets/x86_64-linux/lib/stubs/

R CMD INSTALL .
