#!/bin/sh
set -e

if ! command -v R >/dev/null 2>&1; then
  echo "R executable not found" 1>&2
  exit 1
fi


R -q -e 'if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2", repos = "https://cloud.r-project.org")'
R -q -e 'if (!requireNamespace("processx", quietly = TRUE)) install.packages("processx", repos = "https://cloud.r-project.org")'

R CMD INSTALL .
