name: Testthat

on:
  push:
  workflow_dispatch:

jobs:
  test-base:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install R and dependencies from apt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            r-base \
            r-base-dev \
            r-cran-testthat \
            r-cran-ggplot2 \
            r-cran-processx

      - name: Install package
        run: R CMD INSTALL .

      - name: Run test-base.R
        run: Rscript -e 'source("tests/testthat/helper-gpu.R"); testthat::test_file("tests/testthat/test-base.R")'
